name: efood_multivendor
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#state managment,local storage page navigation, ...
  get: ^4.6.1
  shared_preferences: ^2.0.11
  connectivity: ^3.0.6
  url_launcher: ^6.0.17
  http: ^0.13.4
  path_provider: ^2.0.8
  dot_navigation_bar: ^1.0.1+4
  flutter_feather_icons: ^1.0.3
  flutter_svg: ^0.20.0-nullsafety.0

  # firebase services
  firebase_core: ^1.2.1
  firebase_messaging: ^11.2.4

  # notification services
  flutter_local_notifications: ^9.1.5



  # map services
  geolocator: ^8.0.1
  google_maps_flutter: ^2.1.3
  google_maps_flutter_web: ^0.3.2+1

#  autocomplete
  flutter_typeahead: ^3.2.4

  # Carousel
  carousel_slider: ^4.0.0

  # loader
  shimmer_animation: ^2.1.0+1

  # Image picker
  image_picker: ^0.8.4+4

  # flutter web
  universal_html: ^2.0.8
  universal_ui: ^0.0.8
  webview_flutter: ^3.0.0
  flutter_widget_from_html_core: ^0.8.4
  pointer_interceptor: ^0.9.0+1
  url_strategy: ^0.2.0

  # For authentication
  phone_number: ^0.12.0+2
  country_code_picker: ^2.0.2
  cached_network_image: ^3.2.0
  # google_sign_in: ^5.2.1
  flutter_facebook_auth: ^3.5.7
<<<<<<< HEAD
  firebase_auth: ^3.3.12
=======
  pin_code_fields: ^7.3.0
>>>>>>> 444558b44ead5b25b52ead4c12f1699e5704b5cc

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/image/
    - assets/language/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
        - asset: assets/font/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/font/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/font/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/font/SF-Pro-Text-Black.otf
          weight: 900